import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Shreyash',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'Ayush',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],

    products: [
        {
            // _id: '1',
            name: 'Van Heusen Slim Fit Shirt',
            slug: 'van huesen-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 2599,
            countInStock: 15,
            brand: 'Van Heusen',
            rating: 4.2,
            numReviews: 24,
            description: 'Good Quality Slim Fit Shirt'
        },
        {
            // _id: '2',
            name: 'Cantabill Formal Pant',
            slug: 'cantabill-formal-pant',
            category: 'Pants',
            image: '/images/p2.jpg',
            price: 2799,
            countInStock: 10,
            brand: 'Cantabill',
            rating: 4.5,
            numReviews: 22,
            description: 'Comfortable Formal Wear',
        },
        {
            // _id: '3',
            name: 'Woodland Casual Shirt',
            slug: 'woodland-shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 2499,
            countInStock: 10,
            brand: 'Woodland',
            rating: 4.1,
            numReviews: 24,
            description: 'Casual Wears',
        },
        {
            // _id: '4',
            name: 'Monte Carlo Casual Jeans',
            slug: 'monte carlo-jeans',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 3299,
            countInStock: 10,
            brand: 'Monte Carlo',
            rating: 4.7,
            numReviews: 26,
            description: 'Comfortable Jeans',
        },
        {
            // _id: '5',
            name: 'Allen Solly T-Shirt',
            slug: 'allen-solly-t-shirt',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 1999,
            countInStock: 12,
            brand: 'Allen Solly',
            rating: 4.6,
            numReviews: 15,
            description: 'Collar T-Shirt',
        },
        {
            // _id: '6',
            name: 'Monte Carlo Cargo Jeans',
            slug: 'monte carlo-cargo-jeans',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 3599,
            countInStock: 8,
            brand: 'Monte Carlo',
            rating: 4.4,
            numReviews: 20,
            description: 'Rough and Tough Jeans',
        },
        {
            // _id: '7',
            name: 'Octave T-Shirt',
            slug: 'octave-t-shirt',
            category: 'Shirts',
            image: '/images/p7.jpg',
            price: 1899,
            countInStock: 14,
            brand: 'Octave',
            rating: 4.3,
            numReviews: 24,
            description: 'Round neck T-shirt',
        },
        {
            // _id: '8',
            name: 'Nike Track Pants',
            slug: 'nike-lower',
            category: 'Pants',
            image: '/images/p8.jpg',
            price: 1899,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.7,
            numReviews: 18,
            description: 'Comfortable track pants',
        },
        {
            // _id: '9',
            name: 'Adidas Sports T-shirt',
            slug: 'adidas-t-shirt',
            category: 'Shirts',
            image: '/images/p9.jpg',
            price: 2199,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.6,
            numReviews: 19,
            description: 'Comfortable sports t-shirt',
        },
        {
            // _id: '10',
            name: 'Adidas Sports shorts',
            slug: 'adidas-shorts',
            category: 'Pants',
            image: '/images/p10.jpg',
            price: 2099,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.8,
            numReviews: 25,
            description: 'Comfortable sports shorts',
        },
    ],
};

export default data;